# A collection of test for Project 9 in the Full Stack JavaScript Techdegree


# Tests for the User Routes section of the rubric

### Get User (With Auth)
GET http://localhost:5000/api/users HTTP/1.1
Authorization: Basic joe@smith.com:joepassword

### Create User
POST http://localhost:5000/api/users HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "emailAddress": "john23@smith.com",
  "password": "password"
}

### Create User (Existing Email) - EXCEEDS
POST http://localhost:5000/api/users HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Smith",
  "emailAddress": "joe@smith.com",
  "password": "password"
}


# Tests for the Course Routes section of the rubric

### Get Courses
GET http://localhost:5000/api/courses HTTP/1.1

### Get Course
GET http://localhost:5000/api/courses/1 HTTP/1.1

### Create Course (Minimum Data)
POST http://localhost:5000/api/courses HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{
  "title": "My new course",
  "description": "This is the course I created",
  "userId": 1
}

### Update Course (Minimum Data)
PUT http://localhost:5000/api/courses/1 HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{
	"id": 1,
  "title": "Updated course!",
  "description": "The course description has been updated as well.",
  "userId": 1
}

### Delete Course (With Auth)
DELETE http://localhost:5000/api/courses/4 HTTP/1.1
Authorization: Basic joe@smith.com:joepassword

### Update Course (Not Owner) - EXCEEDS
PUT http://localhost:5000/api/courses/3 HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{
	"id": 3,
  "title": "Updated course!",
  "description": "The course description has been updated as well.",
  "userId": 1
}

### Delete Course (Not Owner) - EXCEEDS
DELETE http://localhost:5000/api/courses/3 HTTP/1.1
Authorization: Basic joe@smith.com:joepassword


# Tests for the Validations section of the rubric

### Create User (Incomplete Data)
POST http://localhost:5000/api/users HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{

}

### Create Course (Incomplete Data)
POST http://localhost:5000/api/courses HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{

}

### Update Course (Incomplete Data)
PUT http://localhost:5000/api/courses/1 HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{
  "title": "",
  "description": ""
}

### Create User (Invalid Email) - EXCEEDS
POST http://localhost:5000/api/users HTTP/1.1
Authorization: Basic joe@smith.com:joepassword
Content-Type: application/json

{
  "firstName": "Sam",
  "lastName": "Smith",
  "emailAddress": "sam.com",
  "password": "password"
}


# Tests for the Permissions section of the rubric

### Get User (No Auth)
GET http://localhost:5000/api/users HTTP/1.1

### Create Course (No Auth, Incomplete Data)
POST http://localhost:5000/api/courses HTTP/1.1
Content-Type: application/json

{

}

### Update Course (No Auth, Incomplete Data)
PUT http://localhost:5000/api/courses/1 HTTP/1.1
Content-Type: application/json

{
  "title": "",
  "description": ""
}

### Delete Course (No Auth)
DELETE http://localhost:5000/api/courses/1 HTTP/1.1


# Tests for catalog search, sort and pagination

### Get Courses (page 2, 5 per page)
GET http://localhost:5000/api/courses?page=2&limit=5 HTTP/1.1

### Get Courses (keyword search, newest first)
GET http://localhost:5000/api/courses?q=wood&sort=-createdAt HTTP/1.1

### Get Courses (title Z-A)
GET http://localhost:5000/api/courses?sort=-title HTTP/1.1

### Get Courses (invalid parameters -> 400 { errors: [...] })
GET http://localhost:5000/api/courses?page=0&limit=500&sort=password HTTP/1.1

### Get Courses (include my archived courses)
GET http://localhost:5000/api/courses?includeArchived=true HTTP/1.1
Authorization: Basic joe@smith.com:joepassword

### Get Courses (includeArchived without auth -> 401)
GET http://localhost:5000/api/courses?includeArchived=true HTTP/1.1


# Tests for archiving and Not Found behaviour

### Get Course (does not exist -> 404 { error: "Course Not Found" })
GET http://localhost:5000/api/courses/9999 HTTP/1.1

### Archive Course (owner)
POST http://localhost:5000/api/courses/1/archive HTTP/1.1
Authorization: Basic joe@smith.com:joepassword

### Get Course (archived, as owner -> 200)
GET http://localhost:5000/api/courses/1 HTTP/1.1
Authorization: Basic joe@smith.com:joepassword

### Get Course (archived, anonymous -> 404)
GET http://localhost:5000/api/courses/1 HTTP/1.1

### Unarchive Course (owner)
POST http://localhost:5000/api/courses/1/unarchive HTTP/1.1
Authorization: Basic joe@smith.com:joepassword

### Archive Course (not the owner -> 403)
POST http://localhost:5000/api/courses/1/archive HTTP/1.1
Authorization: Basic sally@jones.com:sallypassword

### Archive Course (no auth -> 401)
POST http://localhost:5000/api/courses/1/archive HTTP/1.1
